//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetAdoption.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PetAdoptionContextEntities1 : DbContext
    {
        public PetAdoptionContextEntities1()
            : base("name=PetAdoptionContextEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abrigo> Abrigo { get; set; }
        public virtual DbSet<Especie> Especie { get; set; }
        public virtual DbSet<Pet> Pet { get; set; }
        public virtual DbSet<Porte> Porte { get; set; }
        public virtual DbSet<Raca> Raca { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
